### ISSUE TITLE
Typo in the word "length"

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/flymag#19]
Customizer -> blog options, length is spelt wrong for "excerpt length"

**Comment by rodica-andronache** [comment]
Hi @UVLabs , thanks for reporting this :) but, for wp.org themes, we try not to update the strings unless is really necessary, because we don't want to loose the percentages from here https://translate.wordpress.org/projects/wp-themes/flymag
It takes too much to have a string translated/approved there so we try to change the strings at little as possible
