### ISSUE TITLE
Number field not appearing properly

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/flymag#46]
You can see the value in the min/max number field: https://nimbus.everhelper.me/client/notes/share/952589/fdth3ni52gvlgfrwuufy

Using FF on lasest MacOS.

**Comment by rodica-andronache** [comment]
@HardeepAsrani  If you want, you can also fix this (for pro too, if the issue is there too ). There is some inline style added in customizer.php causing this. You'd have just to remove all those inline CSS , for example https://github.com/Codeinwp/flymag/blob/production/inc/customizer.php#L361 . It shouldn't take long :) thanks!
